apiVersion: v1
kind: Service
metadata:
  name: deliveryservice
  labels:
    name: delivery-service
    app: istio-beachshirts

spec:
  ports:
    - targetPort: 50052
      port: 50052

  selector:
      name: delivery-app-pod
      app: istio-beachshirts
