apiVersion: v1
kind: Service
metadata:
  name: shopping-service
  labels:
    name: shopping-service
    app: istio-beachshirts

spec:
  ports:
    - targetPort: 50050
      port: 50050

  selector:
      name: shopping-app-pod
      app: istio-beachshirts
