# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e352ab5843c3166ffc883a957b18af7dbe01fe683eb52096ef8d54c7af4ecd057ada30ef2d81da00ebd44ff5bd37b7b1a55dbfb11da2cb5e060c7c21df04ea8

test:
  secret_key_base: 19a23bb4ec20c78900d8ab8c15982b9f02d0b149682c85d8622de7484a3ac66eedf56cf21c42c3f6d45001c87d3549c32cc37dbcdb8cad9609ada88f36a8de95

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
