server:
  applicationConnectors:
  - type: http
    port: 50052
  adminConnectors:
  - type: http
    port: 50152



# Zipkin-specific options.
zipkin:
  enabled: true
  serviceHost: 127.0.0.1
  servicePort: 50052
  connectTimeout: 10s
  readTimeout: 60s

  collector: http
  baseUrl: http://localhost:9411/

zipkinClient:
  serviceName: delivery
  timeout: 10s